[pytest]
# Directories where pytest looks for tests
testpaths = test

# Test file pattern
python_files = test_*.py

# Custom markers
markers =
    all: run all tests (run only with --all)
    optional: optional tests (run only with --run-optional)
    beta: optional tests (run only with --beta)
    references: optional tests (run only with --references)
    forces: optional tests (run only with --forces)
    optim: optional tests (run only with --optim)
    dynamics: optional tests (run only with --dynamics)
    mc: optional tests (run only with --mc)
    freq: optional tests (run only with --freq)

# Default options
addopts = -ra
